# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'groupmytrip' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for groupmytrip
  pod 'Parse'
  pod 'AFNetworking'
  pod 'SVProgressHUD'
end
